### ISSUE TITLE
Cannot use a level 1 news-server

### ISSUE THREAD

**Issue by ndonkersloot** [nzbgetcom/nzbget#410] opened 2024-10-20 17:48 UTC
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.3-stable

### Platform

Linux/Docker

### Environment

```markdown
Synology DS920+, running on docker using 'nzbgetcom/nzbget:latest' as a image.
```

### Current Behavior

I've always used NZBGet with 1 news-server and decided to add a extra news-server to fill the gap if some articles fails to download. As this is a block news-server I only want to use it as a back-up. So I've configured it as level 1. 

To make sure the news-server is working I disabled the primary server, by doing that I expect the level 1 news-server to download the articles. Instead the download gets queued and doesn't start.
Only if I change the level to 0, the news-server is starting to download.

### Expected Behavior

I expect the news-server to download files at level 1 (or higher) if there is no other news-server available.

### Steps To Reproduce

Add two news-servers. Make one level 0, and another level 1. Disable the level 0 news-server.
In my case downloads only gets queued bu doesn't download.

### Logs

I've looked in the webinterface logs and the docker lgos, no logs occurs when this behavior happens.

### Extra information

I tried other things to fix the issue, like enabling the primary server but with wrong credentials so it actually 'fails', this doesn't make a change.

At of this moment it is impossible for me to use the secondary news-server.

**Comment by dnzbk** [comment] 2024-10-20 18:19
Did you mark your level 0 server as Optional in the news server settings?

**Comment by ndonkersloot** [comment] 2024-10-20 18:30
@dnzbk 
No it isn't marked as optional, if I mark it as optional (just tried) nothing changes.

**Comment by ndonkersloot** [comment] 2024-10-20 18:41
Does it help if I upload my config (excluding usernames and passwords of course)?

**Comment by dnzbk** [comment] 2024-10-20 18:44
Yes, please, thank you.

**Comment by ndonkersloot** [comment] 2024-10-20 18:51
@dnzbk 
[nzbget-20241020-204614.conf.txt](https://github.com/user-attachments/files/17451711/nzbget-20241020-204614.conf.txt)

**Comment by dnzbk** [comment] 2024-10-20 18:56
It looks like the news-server is not set as optional. Did you forget to save the settings?

**Comment by ndonkersloot** [comment] 2024-10-20 19:02
I reverted it because it didn't matter. I can double check that if it is in the export as I save it.

**Comment by ndonkersloot** [comment] 2024-10-20 19:21
I tested some more and you are right, setting it as optional does work, partly.
When setting a wrong username for the first server, to make authentication fail, the level 1 server does indeed download articles!

However, when disabling the first server the second server never gets triggered.

**Comment by dnzbk** [comment] 2024-10-20 19:27
Glad it's working. 
Yes, the first server must be active for everything to work properly.

**Comment by ndonkersloot** [comment] 2024-10-20 19:28
[nzbget.webm](https://github.com/user-attachments/assets/e922ebf0-0f3b-42c5-a55d-edfc11542723)

I've attached a clip showcasing it.
If this is by-design then the issue can be closed.

**Comment by dnzbk** [comment] 2024-10-20 19:41
Thank you. 
Yes, this is by design, although it looks weird at first glance. 
Feel free to close the issue if you're happy with it.

**Closed** 2024-10-20 19:43 UTC
Labels: bug
