### ISSUE TITLE
Mac OS NZBget keeps asking for permission to access removable drive

### ISSUE THREAD

**Issue by ekko20six** [nzbgetcom/nzbget#210] opened 2024-03-26 05:53 UTC
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v23-stable

### Platform

macOS

### Environment

```markdown
Mac Studio running Mac OS 14.4.1 64bit Apple Silicone 
not in docker
```

### Current Behavior

Pop up to provide permission for removable volume despite already providing it.
When I lick allow, the pop up comes back over and over until I do a restart which seems to stop it until it happens again

### Expected Behavior

Click allow once and set and forget

**Comment by luckedea** [comment] 2024-03-26 07:17
@ekko20six 

Can you please clarify:
1. This is USB Storage - correct?
2. Is NZBGet configured to use any of the paths from that USB Storage? (downloads, monitor, etc)

Looks like NZBGet sometimes wants to access it, but doesn't have permissions, so it requests it. Please provide more details.

**Comment by ekko20six** [comment] 2024-03-26 08:03
1. yeah its. USBC SSD HDD
2. yup it uses /Volumes/Complete folder and /Volumes/Incomplete folder both on the same HDD
FYI it was working just fine in the old abandoned version, I only recently found your fork of the project and thats when the issue has started, has used the same volume for quite a while

Odd that it keeps requesting when it has been granted access and most of the time works just fine

**Comment by luckedea** [comment] 2024-03-26 08:20
@ekko20six This is helpful, thanks - I'll do some extra QA similar to your situation.
We didn't change anything related to this behavior though, so it could be the user permission issue on some files on the volume.

Does it still work correctly with Complete/Incomplete volumes? Files are getting created and moved around?

**Comment by ekko20six** [comment] 2024-03-26 08:33
no I think they pause and then after a reboot it picks up like nothing was wrong and finished the download and unpack - I'll observe more closely what happens next time it crops up

**Comment by luckedea** [comment] 2024-03-26 09:26
@ekko20six I assume something is preventing nzbget to access those files. It keeps asking for permissions because it's keep getting rejected in the access.

Is there anything on that machine that can be also using same files and folder, other apps?

It is still a user experience I'd like to improve, but please share as much details as possible as it is still not fully clear what is going on.

**Comment by ekko20six** [comment] 2024-03-27 07:02
Ok so it happened again
files were stuck not downloading and there was no activity 
I checked system settings and NZBget is allowed removable volumes. I turned off allow and back on.
Pop up kept happening.
This time I force quit NZBget from activity monitor and restarted and it happily finished downloading
<img width="180" alt="Screenshot 2024-03-27 at 6 00 29 pm" src="https://github.com/nzbgetcom/nzbget/assets/24378143/76fd52cf-8bda-4242-9ffe-9dc032c88768">
<img width="306" alt="Screenshot 2024-03-27 at 6 00 19 pm" src="https://github.com/nzbgetcom/nzbget/assets/24378143/873aacbf-47f7-4289-9fa8-5c401258b1eb">
<img width="178" alt="Screenshot 2024-03-27 at 5 57 30 pm" src="https://github.com/nzbgetcom/nzbget/assets/24378143/bf82c6ce-a23f-4a71-8c59-a5dedab4362e">
![Screenshot 2024-03-27 at 5 57 16 PM](https://github.com/nzbgetcom/nzbget/assets/24378143/4214d02a-2274-4077-a0e7-85454b4bd4e7)

**Comment by ekko20six** [comment] 2024-03-27 07:13
Happened again as soon as the download has 0 bytes left to download
also notice there are 2 instances of NZBget running in activity monitor - is this normal?
I am trying to read the log file but it's almost 22GB!!!! why is it so large? dates back to June 2023. The log file keeps crashing so I cant view the most recent entries

<img width="782" alt="Screenshot 2024-03-27 at 6 10 09 pm" src="https://github.com/nzbgetcom/nzbget/assets/24378143/fede0c03-72e7-4a9d-88ed-4753fb1e410b">

**Comment by luckedea** [comment] 2024-03-27 09:22
Doing extra QA on this issue to understand if this is Sonoma-specific or not.

**Comment by dnzbk** [comment] 2024-03-27 10:59
@ekko20six 

Having two instances of NZBGet like this is normal. 
The first is the daemon itself, and the second is responsible for the macOS graphics subsystem, e.g the tray icon and the drop-down menu, 

The logging system can be configured at `SETTINGS->LOGGING`.
There should be several options:
 - none - do not write into log file;
 - append - append to the existing log file or create it;

 - reset - delete existing log file on program start and create a new one;

 - rotate - create new log file for each day, delete old files, see option.


The rotation period can also be set there.

**Comment by ekko20six** [comment] 2024-03-27 11:01
Ahh thanks - have fixed the log file. The old one just crashed my computer, it was too big. have it rotating every week now, Cheers

**Comment by ekko20six** [comment] 2024-04-03 07:39
any updates on this one? Now that my log files are working is there anything I can grab to help get to the bottom of it?

**Comment by luckedea** [comment] 2024-04-03 09:23
@ekko20six We did extra QA on this and couldn't confirm this problem on Sonoma/Ventura. @phnzb would be looking at this next week, unfortunately nothing so far. This is specific to just some Sonoma setups.

**Comment by ekko20six** [comment] 2024-04-09 04:15
I switched to the testing 23.1 yesterday (8 April) and havent had the permissions window pup up.
I'll do some further testing to see though
Just thought I'd let you know
D

**Comment by ekko20six** [comment] 2024-05-06 05:24
I just updated to the v24.1 testing released 3 days ago and the problem is back.
Where can I get the 23.1 I had before that was working - am kicking myself for not saving the previous version

**Comment by phnzb** [comment] 2024-05-06 17:46
@ekko20six We didn't modify anything in macOS-specific code that can affects this. In my setup (Mac mini m2 / Sonoma 14.4.1) bug still exists (as month ago...). So it can be coincidence.
Can you please test nzbget install via Homebrew ? On my system it asks for permission once and doesn't ask amymore (after logout/reboot etc.)
Homebrew readme: https://github.com/nzbgetcom/nzbget/blob/develop/osx/brew-info.md
P.S. Homebrew package uses another default config location and must be configured separately.

**Comment by AtumRa** [comment] 2024-05-17 06:58
First off, thanks for resurrecting this orphaned project.
I have tried SABnzbd and don't need all that complication and NZBGet has always worked just fine for me.
I was running the old version 21 without any issues.
Then I saw this project was on Github and downloaded it to give it a try.
I am appreciating the dark-mode on v24. 
So, I am having the same problem as @ekko20six.
My setup:
MacOS 13.6.7 (22G621)
Mac Studio M1 Max
64 GB memory
I use a USB drive for all my downloading and processing with NZBGet.
I just thought I would add that I get the confirmation dialog box for removable volumes any time I try to make a change in the System Settings.
I just updated a program using Homebrew and from the terminal using this command:
brew install --cask timemachineeditor
I got the request for removable volumes from NZBGet when I did that.
I also keep getting a dialog box that asks if I want to allow incoming connections.
<img width="328" alt="image" src="https://github.com/nzbgetcom/nzbget/assets/2613054/d33af253-0584-46f1-80c5-2cf2cbb95796">
I can't imagine why it would need incoming connections so I have been clicking "Deny".
I have switched to version 22 to see if that makes a difference.
I will update when I have more information.

Happy Day!

**Comment by phnzb** [comment] 2024-05-17 12:37
@AtumRa This is a known problem, but at the moment we don't have a reliable solution, still working on it.
We would be very grateful if you could test it for us:
- test the Homebrew version (brew install nzbget) (doesn't have this problem for my tests).
- test the x64 [version](https://github.com/nzbgetcom/nzbget/releases/download/v24.1/nzbget-24.1-bin-macos-x64.zip) (it will work on M1, for me the problem disappeared)

As for allowing incoming connections - NZBGet hosts the WebUI over the network, so that's normal.

**Comment by AtumRa** [comment] 2024-05-18 08:50
Well, I completely uninstalled v21.1 and installed via brew with:
brew install nzbget
Here is a copy of my install session:
[brew log.txt](https://github.com/nzbgetcom/nzbget/files/15360801/brew.log.txt)
I attempted to start nzbget services but this failed as below:
```
Archon@TheStudio ~ % brew services start nzbget
Error: Formula `nzbget` has not implemented #plist, #service or installed a locatable service file
```

Then I tried to install the cask as below:
```
Archon@TheStudio ~ % brew install --cask nzbget
Warning: Not upgrading nzbget, the latest version is already installed
```
Brew did not install the cask version of nzbget from the command above.
So, I returned to v21.1 as it seems to be working for me and I will have to go without dark mode for now. 🙁
Sorry I could not be of more help.
Happy Day!

**Comment by phnzb** [comment] 2024-05-18 10:00
@AtumRa You have outdated nzbget cask installed, so the nzbget formula is not linked correctly (per log `==> nzbget cask is installed, skipping link.`). Please remove nzbget cask and reinstall nzbget 
```
brew remove nzbget --cask
brew remove nzbget
brew install nzbget
```

**Comment by AtumRa** [comment] 2024-05-19 09:34
I followed your instructions and got NZBGet installed and running and restored my config files from v21.1.
Unfortunately, it would not connect to, and download from, my newsgroup provider.
I use news.newshosting.com.
I tested the connection and got this response:
<img width="424" alt="Screenshot 2024-05-19 at 5 31 59 AM" src="https://github.com/nzbgetcom/nzbget/assets/2613054/87ea2781-21a3-42ad-8231-6c0c104d34cd">
This config file works fine with v21.1 and works for the other versions except for the bug regarding removable volumes.
Hopefully this information is helpful.
Happy Day!

**Comment by phnzb** [comment] 2024-05-20 09:33
@AtumRa nzbget Homebrew version is configured by default with CertCheck disabled.

If you want to get CertCheck working, you must download root certificates and configure nzbget (imported config overwrites defaults and caused yours error).

From terminal:
```
curl -o /opt/homebrew/etc/cacert.pem https://curl.se/ca/cacert.pem
```
Then Settings -> PATHS -> CertStore -> change to `/opt/homebrew/etc/cacert.pem` and reload nzbget.

Or you can disable CertCheck in Settings -> SECURITY -> CertCheck -> No and reload nzbget.

**Comment by naltsta** [comment] 2024-05-30 12:39
I have this issue on Sonoma 14.5

Interestingly I get popups requesting access to both removable volume and the downloads folder on repeat.

**Comment by hpnas47** [comment] 2024-08-14 16:25
I have this issue on the latest issue of Sonoma on my Mac Studio using a Synology NAS as the end point for my media.  Same thing, get pop ups asking to allow access to NAS (Media Folder) and Downloads folder (local Mac).  Nothing seems to be able to rectify it, to the point where it's rendering my set up unusable b/c my auto downloaders (Sonarr, Radarr) can't move files to the NAS when downloads are complete

**Comment by wasspoca** [comment] 2024-10-29 17:04
> This is a known problem, but at the moment we don't have a reliable solution, still working on it. We would be very grateful if you could test it for us:
> 
> * test the Homebrew version (brew install nzbget) (doesn't have this problem for my tests).
> * test the x64 [version](https://github.com/nzbgetcom/nzbget/releases/download/v24.1/nzbget-24.1-bin-macos-x64.zip) (it will work on M1, for me the problem disappeared)
> 
> As for allowing incoming connections - NZBGet hosts the WebUI over the network, so that's normal.

@phnzb Thanks a lot, I had the same issue and the Homebrew version solved it, no more pop-ups asking for access permission.
- macOS Sonoma 14.3.1
- Synology DS413j mounted volume as a destination folder
- Nzbget 24.3 (universal binary) -> Nzbget 24.3 (Homebrew)

**Comment by naltsta** [comment] 2024-10-29 20:50
I've just go the home-brew version up and running but get this message in settings. Looks like it wants me to edit a file to point to itself?... Any help appreciated.

Loading configuration failed

Could not load template configuration file nzbget.conf. The file contains descriptions of options and is needed to display settings page. The file comes with NZBGet distribution archive and is usually automatically installed into the right location. This seems not to be a case with your installation though.

Please edit your configuration file (/opt/homebrew/etc/nzbget.conf) in a text editor and set the option ConfigTemplate to point to the template configuration file nzbget.conf.

**Comment by phnzb** [comment] 2024-10-30 12:25
@naltsta Thank you for the report! This is caused by changed behavior of installing config template on POSIX systems. This bug was already fixed in develop branch and will be included in next release.
As workaround for current homebrew version you can:
- install current develop (testing) version via
```brew install nzbget --HEAD```
or
- create config template from default config. Run from Terminal:
```cp /opt/homebrew/Cellar/nzbget/24.3/.bottle/etc/nzbget.conf /opt/homebrew/share/nzbget/nzbget.conf```

**Closed** 2024-11-18 15:58 UTC
Labels: bug
